name: First Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello world"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Say Bye
        run: echo "Bye world"
